const CONFIG = {
  HANZI_SHEET: 'Hanzi',
  CACHE_SHEET: 'AI_CACHE',
  HEADER_ROW: 1,
  HEADER_WIDTH: 28,

  COL_INPUT_TEXT: 1,
  COL_NORMALIZED_TEXT: 2,
  COL_PINYIN: 3,
  COL_MEANINGS_VI: 4,
  COL_HAN_VIET: 5,
  COL_TRADITIONAL_VARIANT: 6,

  COL_MAIN_RADICALS: 7,
  COL_COMPONENT_BREAKDOWN_JSON: 8,
  COL_RADICAL_SUMMARY: 9,

  COL_HSK_LEVEL: 10,
  COL_PART_OF_SPEECH: 11,
  COL_TOPIC_TAGS: 12,
  COL_EXAMPLES: 13,
  COL_SIMILAR_CHARS: 14,

  COL_CHARACTER_STRUCTURE_TYPE: 15,
  COL_STRUCTURE_EXPLANATION: 16,
  COL_MNEMONIC: 17,
  COL_NOTES: 18,
  COL_SOURCE_CONFIDENCE: 19,
  COL_AMBIGUITY_FLAG: 20,
  COL_AMBIGUITY_NOTE: 21,
  COL_READING_CANDIDATES: 22,
  COL_REVIEW_STATUS: 23,
  COL_AI_STATUS: 24,
  COL_UPDATED_AT: 25,

  COL_LAST_API_KEY: 26,      // Z
  COL_LAST_MODEL: 27,        // AA
  COL_LAST_DURATION_MS: 28,  // AB

  GEMINI_MODEL_WEIGHTS: [
    { model: 'gemini-3.1-flash-lite-preview', weight: 5 },
    { model: 'gemini-2.5-flash', weight: 2 },
    { model: 'gemini-2.5-flash-lite', weight: 1 },
    { model: 'gemini-3-flash-preview', weight: 1 }
  ],

  MAX_RETRY_ATTEMPTS_PER_MODEL: 1,
  BASE_RETRY_DELAY_MS: 1500,
  MAX_RETRY_DELAY_MS: 12000,

  AI_MICRO_BATCH_SIZE: 3,
  WORKER_COUNT: 5,
  WORKER_TRIGGER_INTERVAL_MIN: 5,
  RECOVERY_TRIGGER_INTERVAL_MIN: 15,

  STALE_PROCESSING_MINUTES: 15,
  INLINE_PASTE_THRESHOLD_ROWS: 1,
  ENABLE_INLINE_SINGLE_CELL_PROCESSING: true,
  MANUAL_PROCESS_BATCH_LIMIT: 3,
  CLAIM_LOCK_TIMEOUT_MS: 3000,
  ROUTE_LOCK_TIMEOUT_MS: 3000,
  GEMINI_ROUTE_STATE_PROPERTY: 'GEMINI_ROUTE_STATE'
};

const HANZI_HEADERS = [
  'input_text',
  'normalized_text',
  'pinyin',
  'meanings_vi',
  'han_viet',
  'traditional_variant',
  'main_radicals',
  'component_breakdown_json',
  'radical_summary',
  'hsk_level',
  'part_of_speech',
  'topic_tags',
  'examples',
  'similar_chars',
  'character_structure_type',
  'structure_explanation',
  'mnemonic',
  'notes',
  'source_confidence',
  'ambiguity_flag',
  'ambiguity_note',
  'reading_candidates',
  'review_status',
  'ai_status',
  'updated_at',
  'last_used_api_key',
  'last_used_model',
  'last_duration_ms'
];

const ALLOWED_TOPIC_TAGS = [
  'hoc_tap',
  'truong_hoc',
  'giao_duc',
  'mon_hoc',
  'hoc_thuat',
  'luyen_tap',
  'kiem_tra',
  'thi_cu',

  'ngon_ngu',
  'giao_tiep',
  'hoi_thoai',
  'chao_hoi',
  'gioi_thieu',
  'cau_hoi',
  'tra_loi',
  'dong_y',
  'tu_choi',
  'bieu_dat',
  'phat_am',
  'viet',
  'doc',
  'nghe',
  'noi',

  'con_nguoi',
  'ca_nhan',
  'gia_dinh',
  'quan_he',
  'ban_be',
  'hon_nhan',
  'tre_em',
  'nguoi_lon',
  'gioi_tinh',
  'tinh_cach',
  'tinh_trang',
  'vai_tro',
  'nghe_nghiep',
  'chuc_danh',

  'doi_song',
  'sinh_hoat',
  'nha_cua',
  'vat_dung',
  'do_dung',
  'noi_that',
  'dien_may',
  'an_uong',
  'nau_an',
  'do_an',
  'do_uong',
  'mua_sam',
  'tieu_dung',

  'hanh_dong',
  'di_chuyen',
  'lam_viec',
  'nghi_ngoi',
  'giai_tri',
  'the_thao',
  'tro_choi',

  'thoi_gian',
  'ngay_thang',
  'nam',
  'gio_time',
  'qua_khu',
  'hien_tai',
  'tuong_lai',
  'tan_suat',
  'thoi_diem',
  'dia_diem',
  'phuong_huong',
  'vi_tri',
  'khong_gian',

  'thien_nhien',
  'thoi_tiet',
  'khi_hau',
  'dong_vat',
  'thuc_vat',
  'cay_coi',
  'song_nui',
  'bien',
  'mua',
  'gio_wind',
  'nhiet_do',

  'tru_tuong',
  'y_nghia',
  'tu_duy',
  'nhan_thuc',
  'logic',
  'ly_luan',
  'khai_niem',
  'gia_tri',
  'muc_tieu',
  'y_dinh',
  'quyet_dinh',

  'cam_xuc',
  'tinh_cam',
  'vui',
  'buon',
  'tuc_gian',
  'so_hai',
  'yeu_thich',
  'ghet',
  'lo_lang',
  'hanh_phuc',
  'met_moi',

  'suc_khoe',
  'benh_tat',
  'thuoc',
  'bac_si',
  'dieu_tri',
  'co_the',
  'bo_phan_co_the',
  'cam_giac',
  'an_toan',

  'giao_thong',
  'phuong_tien',
  'xe_co',
  'oto',
  'xe_may',
  'tau',
  'may_bay',
  'duong_bo',
  'duong_sat',
  'duong_hang_khong',

  'cong_nghe',
  'may_tinh',
  'internet',
  'phan_mem',
  'ung_dung',
  'du_lieu',
  'ai',
  'lap_trinh',
  'he_thong',
  'mang',

  'van_hoa',
  'am_nhac',
  'phim_anh',
  'truyen',
  'nghe_thuat',
  'le_hoi',
  'du_lich',

  'chinh_tri',
  'phap_luat',
  'luat',
  'chinh_sach',
  'quyen_luc',
  'chinh_phu',
  'xa_hoi',
  'an_ninh',
  'quan_su',

  'so_dem',
  'so_luong',
  'so_thu_tu',
  'do_luong',
  'don_vi',
  'mau_sac',
  'kich_thuoc',
  'hinh_dang',

  'pho_bien',
  'co_ban',
  'nang_cao',
  'de_nham',
  'da_nghia',
  'da_am',
  'quan_trong',
  'thuong_gap'
];

const TAG_TO_GROUP = {
  hoc_tap: 'education',
  truong_hoc: 'education',
  giao_duc: 'education',
  mon_hoc: 'education',
  hoc_thuat: 'education',
  luyen_tap: 'education',
  kiem_tra: 'education',
  thi_cu: 'education',

  ngon_ngu: 'communication',
  giao_tiep: 'communication',
  hoi_thoai: 'communication',
  chao_hoi: 'communication',
  gioi_thieu: 'communication',
  cau_hoi: 'communication',
  tra_loi: 'communication',
  dong_y: 'communication',
  tu_choi: 'communication',
  bieu_dat: 'communication',
  phat_am: 'communication',
  viet: 'communication',
  doc: 'communication',
  nghe: 'communication',
  noi: 'communication',

  con_nguoi: 'people',
  ca_nhan: 'people',
  gia_dinh: 'people',
  quan_he: 'people',
  ban_be: 'people',
  hon_nhan: 'people',
  tre_em: 'people',
  nguoi_lon: 'people',
  gioi_tinh: 'people',
  tinh_cach: 'people',
  tinh_trang: 'people',
  vai_tro: 'people',
  nghe_nghiep: 'people',
  chuc_danh: 'people',

  doi_song: 'lifestyle',
  sinh_hoat: 'lifestyle',
  nha_cua: 'lifestyle',
  vat_dung: 'lifestyle',
  do_dung: 'lifestyle',
  noi_that: 'lifestyle',
  dien_may: 'lifestyle',
  an_uong: 'lifestyle',
  nau_an: 'lifestyle',
  do_an: 'lifestyle',
  do_uong: 'lifestyle',
  mua_sam: 'lifestyle',
  tieu_dung: 'lifestyle',

  hanh_dong: 'action',
  di_chuyen: 'action',
  lam_viec: 'action',
  nghi_ngoi: 'action',
  giai_tri: 'action',
  the_thao: 'action',
  tro_choi: 'action',

  thoi_gian: 'time_space',
  ngay_thang: 'time_space',
  nam: 'time_space',
  gio_time: 'time_space',
  qua_khu: 'time_space',
  hien_tai: 'time_space',
  tuong_lai: 'time_space',
  tan_suat: 'time_space',
  thoi_diem: 'time_space',
  dia_diem: 'time_space',
  phuong_huong: 'time_space',
  vi_tri: 'time_space',
  khong_gian: 'time_space',

  thien_nhien: 'nature',
  thoi_tiet: 'nature',
  khi_hau: 'nature',
  dong_vat: 'nature',
  thuc_vat: 'nature',
  cay_coi: 'nature',
  song_nui: 'nature',
  bien: 'nature',
  mua: 'nature',
  gio_wind: 'nature',
  nhiet_do: 'nature',

  tru_tuong: 'abstract',
  y_nghia: 'abstract',
  tu_duy: 'abstract',
  nhan_thuc: 'abstract',
  logic: 'abstract',
  ly_luan: 'abstract',
  khai_niem: 'abstract',
  gia_tri: 'abstract',
  muc_tieu: 'abstract',
  y_dinh: 'abstract',
  quyet_dinh: 'abstract',

  cam_xuc: 'emotion',
  tinh_cam: 'emotion',
  vui: 'emotion',
  buon: 'emotion',
  tuc_gian: 'emotion',
  so_hai: 'emotion',
  yeu_thich: 'emotion',
  ghet: 'emotion',
  lo_lang: 'emotion',
  hanh_phuc: 'emotion',
  met_moi: 'emotion',

  suc_khoe: 'health',
  benh_tat: 'health',
  thuoc: 'health',
  bac_si: 'health',
  dieu_tri: 'health',
  co_the: 'health',
  bo_phan_co_the: 'health',
  cam_giac: 'health',
  an_toan: 'health',

  giao_thong: 'transport',
  phuong_tien: 'transport',
  xe_co: 'transport',
  oto: 'transport',
  xe_may: 'transport',
  tau: 'transport',
  may_bay: 'transport',
  duong_bo: 'transport',
  duong_sat: 'transport',
  duong_hang_khong: 'transport',

  cong_nghe: 'technology',
  may_tinh: 'technology',
  internet: 'technology',
  phan_mem: 'technology',
  ung_dung: 'technology',
  du_lieu: 'technology',
  ai: 'technology',
  lap_trinh: 'technology',
  he_thong: 'technology',
  mang: 'technology',

  van_hoa: 'culture',
  am_nhac: 'culture',
  phim_anh: 'culture',
  truyen: 'culture',
  nghe_thuat: 'culture',
  le_hoi: 'culture',
  du_lich: 'culture',

  chinh_tri: 'society',
  phap_luat: 'society',
  luat: 'society',
  chinh_sach: 'society',
  quyen_luc: 'society',
  chinh_phu: 'society',
  xa_hoi: 'society',
  an_ninh: 'society',
  quan_su: 'society',

  so_dem: 'quantity',
  so_luong: 'quantity',
  so_thu_tu: 'quantity',
  do_luong: 'quantity',
  don_vi: 'quantity',
  mau_sac: 'quantity',
  kich_thuoc: 'quantity',
  hinh_dang: 'quantity'
};

const RADICAL_LIST = [
  "Nhất 一",
  "Cổn 丨",
  "Chủ 丶",
  "Phiệt 丿",
  "Ất 乙",
  "Quyết 亅",
  "Nhị 二",
  "Đầu 亠",
  "Nhân 人 (亻)",
  "Nhi 儿",
  "Nhập 入",
  "Bát 八 (丷)",
  "Quynh 冂",
  "Mịch 冖",
  "Băng 冫",
  "Kỷ 几",
  "Khảm 凵",
  "Đao 刀 (刂)",
  "Lực 力",
  "Bao 勹",
  "Chủy 匕",
  "Phương 匚",
  "Hệ 匸",
  "Thập 十",
  "Bốc 卜",
  "Tiết 卩 (⺋)",
  "Hán 厂",
  "Tư 厶",
  "Hựu 又",
  "Khẩu 口",
  "Vi 囗",
  "Thổ 土",
  "Sĩ 士",
  "Tuy 夂",
  "Truy 夊",
  "Tịch 夕",
  "Đại 大",
  "Nữ 女",
  "Tử 子",
  "Miên 宀",
  "Thốn 寸",
  "Tiểu 小 (⺌)",
  "Uông 尢 (尣)",
  "Thi 尸",
  "Triệt 屮",
  "Sơn 山",
  "Xuyên 巛 (川)",
  "Công 工",
  "Kỷ 己",
  "Cân 巾",
  "Can 干",
  "Yêu 幺",
  "Nghiễm 广",
  "Dẫn 廴",
  "Củng 廾",
  "Dặc 弋",
  "Cung 弓",
  "Kệ 彐 (彑)",
  "Sam 彡",
  "Xích 彳",
  "Tâm 心 (忄, ⺗)",
  "Qua 戈",
  "Hộ 戶 (户)",
  "Thủ 手 (扌)",
  "Chi 支",
  "Phộc 攴 (攵)",
  "Văn 文",
  "Đẩu 斗",
  "Cân 斤",
  "Phương 方",
  "Vô 无 (旡)",
  "Nhật 日",
  "Viết 曰",
  "Nguyệt 月 (⺝ khi làm bộ thịt)",
  "Mộc 木",
  "Khiếm 欠",
  "Chỉ 止",
  "Đãi 歹 (歺)",
  "Ân 殳",
  "Mẫu 毋 (母 liên quan hình thể)",
  "Tỷ 比",
  "Mao 毛",
  "Thị 氏",
  "Khí 气",
  "Thủy 水 (氵, 氺)",
  "Hỏa 火 (灬)",
  "Trảo 爪 (爫)",
  "Phụ 父",
  "Hào 爻",
  "Phiến 爿 (丬)",
  "Nha 牙",
  "Ngưu 牛 (牜)",
  "Khuyển 犬 (犭)",
  "Huyền 玄",
  "Ngọc 玉 (王, ⺩)",
  "Qua 瓜",
  "Ngõa 瓦",
  "Cam 甘",
  "Sinh 生",
  "Dụng 用",
  "Điền 田",
  "Sơ 疋 (⺪)",
  "Nạch 疒",
  "Bạch 白",
  "Bì 皮",
  "Mãnh 皿",
  "Mục 目",
  "Mâu 矛",
  "Thỉ 矢",
  "Thạch 石",
  "Thị 示 (礻)",
  "Lộc 禸",
  "Hòa 禾",
  "Huyệt 穴",
  "Lập 立",
  "Trúc 竹 (⺮)",
  "Mễ 米",
  "Mịch 糸 (糹, 纟)",
  "Phẫu 缶",
  "Võng 网 (罒, 罓)",
  "Dương 羊 (⺶)",
  "Vũ 羽",
  "Lão 老 (耂)",
  "Nhi 而",
  "Nhĩ 耳",
  "Bút 聿 (⺻)",
  "Nhục 肉 (⺼)",
  "Thần 臣",
  "Tự 自",
  "Chí 至",
  "Cữu 臼",
  "Thiệt 舌",
  "Thuấn 舛",
  "Chu 舟",
  "Cấn 艮",
  "Sắc 色",
  "Thảo 艸 (艹)",
  "Hổ 虍",
  "Trùng 虫",
  "Huyết 血",
  "Hành 行",
  "Y 衣 (衤)",
  "Tây 襾 (覀)",
  "Kiến 見 (见)",
  "Giác 角",
  "Ngôn 言 (訁, 讠)",
  "Cốc 谷",
  "Đậu 豆",
  "Thỉ 豕",
  "Trĩ 豸",
  "Bối 貝 (贝)",
  "Xích 赤",
  "Tẩu 走",
  "Túc 足 (𧾷)",
  "Thân 身",
  "Xa 車 (车)",
  "Tân 辛",
  "Thần 辰",
  "Sước 辵 (辶)",
  "Ấp 邑 (阝– phải)",
  "Dậu 酉",
  "Thích 釆",
  "Lý 里",
  "Kim 金 (釒, 钅)",
  "Trường 長 (长)",
  "Môn 門 (门)",
  "Phụ 阜 (阝– trái)",
  "Lệ 隶",
  "Tuy 隹",
  "Vũ 雨",
  "Thanh 青",
  "Phi 非",
  "Diện 面",
  "Cách 革",
  "Vi 韋 (韦)",
  "Âm 音",
  "Hiệt 頁 (页)",
  "Phong 風 (风)",
  "Phi 飛 (飞)",
  "Thực 食 (飠, 饣)",
  "Thủ 首",
  "Hương 香",
  "Mã 馬 (马)",
  "Cốt 骨",
  "Cao 高",
  "Phát 髟",
  "Đấu 鬥 (斗)",
  "Mạch 鬯",
  "Cách cách 鬲",
  "Quỷ 鬼",
  "Ngư 魚 (鱼)",
  "Điểu 鳥 (鸟)",
  "Lỗ 鹵 (卤)",
  "Lộc 鹿",
  "Mạch 麥 (麦)",
  "Ma 麻",
  "Hoàng 黃 (黄)",
  "Thử 黍",
  "Hắc 黑",
  "Đại 黹",
  "Thằng 黽 (黾)",
  "Đỉnh 鼎",
  "Cổ 鼓",
  "Thử 鼠",
  "Tỵ 鼻",
  "Tề 齊 (齐)",
  "Xỉ 齒 (齿)",
  "Long 龍 (龙)",
  "Quy 龜 (龟)",
  "Dược 龠",
];
