export const ALLOWED_TOPIC_TAGS = [
  "con_nguoi", "ca_nhan", "gia_dinh", "quan_he", "ban_be", "hon_nhan", "tre_em", "nguoi_lon", "gioi_tinh", "tinh_cach", "tinh_trang", "vai_tro", "nghe_nghiep", "chuc_danh", "xa_hoi", "van_hoa", "tap_quan", "truyen_thong", "giao_tiep", "hoi_thoai", "chao_hoi", "gioi_thieu", "cau_hoi", "tra_loi", "dong_y", "tu_choi", "ngon_ngu", "ngu_phap", "tu_vung", "phat_am", "viet", "doc", "nghe", "noi", "bieu_dat", "hoc_tap", "truong_hoc", "giao_duc", "mon_hoc", "hoc_thuat", "kien_thuc", "ky_nang", "luyen_tap", "kiem_tra", "thi_cu", "nghien_cuu", "giang_day", "cong_viec", "van_phong", "kinh_doanh", "thuong_mai", "tai_chinh", "tien_bac", "luong", "hop_dong", "dau_tu", "kinh_te", "san_xuat", "doi_song", "sinh_hoat", "nha_cua", "vat_dung", "do_dung", "noi_that", "dien_may", "an_uong", "nau_an", "do_an", "do_uong", "mua_sam", "tieu_dung", "hanh_dong", "di_chuyen", "chay", "di_bo", "den", "roi_di", "lam_viec", "hoc", "nghi_ngoi", "giai_tri", "the_thao", "tro_choi", "thoi_gian", "ngay_thang", "nam", "gio_time", "qua_khu", "hien_tai", "tuong_lai", "tan_suat", "thoi_diem", "dia_diem", "phuong_huong", "vi_tri", "khong_gian", "thien_nhien", "thoi_tiet", "khi_hau", "dong_vat", "thuc_vat", "cay_coi", "song_nui", "bien", "mua", "gio_wind", "nhiet_do", "tru_tuong", "y_nghia", "tu_duy", "nhan_thuc", "logic", "ly_luan", "khai_niem", "gia_tri", "muc_tieu", "y_dinh", "quyet_dinh", "cam_xuc", "tinh_cam", "vui", "buon", "tuc_gian", "so_hai", "yeu_thich", "ghet", "lo_lang", "hanh_phuc", "met_moi", "suc_khoe", "ben_tat", "thuoc", "bac_si", "dieu_tri", "co_the", "bo_phan_co_the", "cam_giac", "an_toan", "giao_thong", "phuong_tien", "xe_co", "oto", "xe_may", "tau", "may_bay", "duong_bo", "duong_sat", "duong_hang_khong", "cong_nghe", "may_tinh", "internet", "phan_mem", "ung_dung", "du_lieu", "ai", "lap_trinh", "he_thong", "mang", "am_nhac", "phim_anh", "truyen", "nghe_thuat", "le_hoi", "du_lich", "chinh_tri", "phap_luat", "luat", "chinh_sach", "quyen_luc", "chinh_phu", "an_ninh", "quan_su", "so_dem", "so_luong", "so_thu_tu", "do_luong", "don_vi", "mau_sac", "kich_thuoc", "hinh_dang", "pho_bien", "co_ban", "nang_cao", "de_nham", "da_nghia", "da_am", "quan_trong", "thuong_gap"
];

export const PART_OF_SPEECH_LIST = [
  "danh_tu", "dong_tu", "tinh_tu", "pho_tu", "luong_tu", "dai_tu", "gioi_tu", "tro_tu", "so_tu", "da_loai_tu", "unknown"
];

export const CHARACTER_STRUCTURE_LIST = [
  "hinh_thanh", "hoi_y", "tuong_hinh", "chi_su", "gia_ta", "khac", "khong_ro"
];

// Human readable mappings
export const TAG_LABELS: Record<string, string> = {
  // Topics
  con_nguoi: "Con người",
  ca_nhan: "Cá nhân",
  gia_dinh: "Gia đình",
  quan_he: "Quan hệ",
  ban_be: "Bạn bè",
  hon_nhan: "Hôn nhân",
  tre_em: "Trẻ em",
  nguoi_lon: "Người lớn",
  gioi_tinh: "Giới tính",
  tinh_cach: "Tính cách",
  tinh_trang: "Tình trạng",
  vai_tro: "Vai trò",
  nghe_nghiep: "Nghề nghiệp",
  chuc_danh: "Chức danh",
  xa_hoi: "Xã hội",
  van_hoa: "Văn hóa",
  tap_quan: "Tập quán",
  truyen_thong: "Truyền thống",
  giao_tiep: "Giao tiếp",
  hoi_thoai: "Hội thoại",
  chao_hoi: "Chào hỏi",
  gioi_thieu: "Giới thiệu",
  cau_hoi: "Câu hỏi",
  tra_loi: "Trả lời",
  dong_y: "Đồng ý",
  tu_choi: "Từ chối",
  ngon_ngu: "Ngôn ngữ",
  ngu_phap: "Ngữ pháp",
  tu_vung: "Từ vựng",
  phat_am: "Phát âm",
  viet: "Viết",
  doc: "Đọc",
  nghe: "Nghe",
  noi: "Nói",
  bieu_dat: "Biểu đạt",
  hoc_tap: "Học tập",
  truong_hoc: "Trường học",
  giao_duc: "Giáo dục",
  mon_hoc: "Môn học",
  hoc_thuat: "Học thuật",
  kien_thuc: "Kiến thức",
  ky_nang: "Kỹ năng",
  luyen_tap: "Luyện tập",
  kiem_tra: "Kiểm tra",
  thi_cu: "Thi cử",
  nghien_cuu: "Nghiên cứu",
  giang_day: "Giảng dạy",
  cong_viec: "Công việc",
  van_phong: "Văn phòng",
  kinh_doanh: "Kinh doanh",
  thuong_mai: "Thương mại",
  tai_chinh: "Tài chính",
  tien_bac: "Tiền bạc",
  luong: "Lương",
  hop_dong: "Hợp đồng",
  dau_tu: "Đầu tư",
  kinh_te: "Kinh tế",
  san_xuat: "Sản xuất",
  doi_song: "Đời sống",
  sinh_hoat: "Sinh hoạt",
  nha_cua: "Nhà cửa",
  vat_dung: "Vật dụng",
  do_dung: "Đồ dùng",
  noi_that: "Nội thất",
  dien_may: "Điện máy",
  an_uong: "Ăn uống",
  nau_an: "Nấu ăn",
  do_an: "Đồ ăn",
  do_uong: "Đồ uống",
  mua_sam: "Mua sắm",
  tieu_dung: "Tiêu dùng",
  hanh_dong: "Hành động",
  di_chuyen: "Di chuyển",
  chay: "Chạy",
  di_bo: "Đi bộ",
  den: "Đến",
  roi_di: "Rời đi",
  lam_viec: "Làm việc",
  hoc: "Học",
  nghi_ngoi: "Nghỉ ngơi",
  giai_tri: "Giải trí",
  the_thao: "Thể thao",
  tro_choi: "Trò chơi",
  thoi_gian: "Thời gian",
  ngay_thang: "Ngày tháng",
  nam: "Năm",
  gio_time: "Giờ",
  qua_khu: "Quá khứ",
  hien_tai: "Hiện tại",
  tuong_lai: "Tương lai",
  tan_suat: "Tần suất",
  thoi_diem: "Thời điểm",
  dia_diem: "Địa điểm",
  phuong_huong: "Phương hướng",
  vi_tri: "Vị trí",
  khong_gian: "Không gian",
  thien_nhien: "Thiên nhiên",
  thoi_tiet: "Thời tiết",
  khi_hau: "Khí hậu",
  dong_vat: "Động vật",
  thuc_vat: "Thực vật",
  cay_coi: "Cây cối",
  song_nui: "Sông núi",
  bien: "Biển",
  mua: "Mưa",
  gio_wind: "Gió",
  nhiet_do: "Nhiệt độ",
  tru_tuong: "Trừu tượng",
  y_nghia: "Ý nghĩa",
  tu_duy: "Tư duy",
  nhan_thuc: "Nhận thức",
  logic: "Logic",
  ly_luan: "Lý luận",
  khai_niem: "Khái niệm",
  gia_tri: "Giá trị",
  muc_tieu: "Mục tiêu",
  y_dinh: "Ý định",
  quyet_dinh: "Quyết định",
  cam_xuc: "Cảm xúc",
  tinh_cam: "Tình cảm",
  vui: "Vui",
  buon: "Buồn",
  tuc_gian: "Tức giận",
  so_hai: "Sợ hãi",
  yeu_thich: "Yêu thích",
  ghet: "Ghét",
  lo_lang: "Lo lắng",
  han_phuc: "Hạnh phúc",
  met_moi: "Mệt mỏi",
  suc_khoe: "Sức khỏe",
  benh_tat: "Bệnh tật",
  thuoc: "Thuốc",
  bac_si: "Bác sĩ",
  dieu_tri: "Điều trị",
  co_the: "Cơ thể",
  bo_phan_co_the: "Bộ phận cơ thể",
  cam_giac: "Cảm giác",
  an_toan: "An toàn",
  giao_thong: "Giao thông",
  phuong_tien: "Phương tiện",
  xe_co: "Xe cộ",
  oto: "Ô tô",
  xe_may: "Xe máy",
  tau: "Tàu",
  may_bay: "Máy bay",
  duong_bo: "Đường bộ",
  duong_sat: "Đường sắt",
  duong_hang_khong: "Đường hàng không",
  cong_nghe: "Công nghệ",
  may_tinh: "Máy tính",
  internet: "Internet",
  phan_mem: "Phần mềm",
  ung_dung: "Ứng dụng",
  du_lieu: "Dữ liệu",
  ai: "AI/Trí tuệ nhân tạo",
  lap_trinh: "Lập trình",
  he_thong: "Hệ thống",
  mang: "Mạng",
  am_nhac: "Âm nhạc",
  phim_anh: "Phim ảnh",
  truyen: "Truyện",
  nghe_thuat: "Nghệ thuật",
  le_hoi: "Lễ hội",
  du_lich: "Du lịch",
  chinh_tri: "Chính trị",
  phap_luat: "Pháp luật",
  luat: "Luật",
  chinh_sach: "Chính sách",
  quyen_luc: "Quyền lực",
  chinh_phu: "Chính phủ",
  an_ninh: "An ninh",
  quan_su: "Quân sự",
  so_dem: "Số đếm",
  so_luong: "Số lượng",
  so_thu_tu: "Số thứ tự",
  do_luong: "Đo lường",
  don_vi: "Đơn vị",
  mau_sac: "Màu sắc",
  kich_thuoc: "Kích thước",
  hinh_dang: "Hình dáng",
  pho_bien: "Phổ biến",
  co_bat: "Cơ bản",
  co_ban: "Cơ bản",
  nang_cao: "Nâng cao",
  de_nham: "Dễ nhầm",
  da_nghia: "Đa nghĩa",
  da_am: "Đa âm",
  quan_trong: "Quan trọng",
  thuong_gap: "Thường gặp",

  // POS
  danh_tu: "Danh từ",
  dong_tu: "Động từ",
  tinh_tu: "Tính từ",
  pho_tu: "Phó từ",
  luong_tu: "Lượng từ",
  dai_tu: "Đại từ",
  gioi_tu: "Giới từ",
  tro_tu: "Trợ từ",
  so_tu: "Số từ",
  da_loai_tu: "Đa loại từ",
  unknown: "Không rõ",

  // Structures
  hinh_thanh: "Hình thanh (Phonetic-Semantic)",
  hoi_y: "Hội ý (Ideogrammatic)",
  tuong_hinh: "Tượng hình (Pictographic)",
  chi_su: "Chỉ sự (Indicative)",
  gia_ta: "Giả tá (Rebus)",
  khac: "Khác",
  khong_ro: "Không rõ"
};
